# Generated by Django 5.1.1 on 2024-09-13 13:47

import services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=services.get_path_upload_comments_images),
        ),
    ]
